version: '2'
services:
  web:
    image: webdevops/php-apache-dev:ubuntu-16.04
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST: database
      DB_USER: spacepunks
      DB_PASSWORD: spacepunks
      DB_NAME: spacepunks
      ADMIN_NAME: admin
      ADMIN_PASSWORD: admin
      ADMIN_MAIL: mail@example.com
    ports:
      - 8080:80
    networks:
      - spacepunks
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spacepunks
      MYSQL_USER: spacepunks
      MYSQL_PASSWORD: spacepunks
    ports:
      - 3306:3306
    networks:
      spacepunks:
        aliases:
          - database

networks:
  spacepunks: